exclude: '.git|migrations'

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 'master'
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'master'
  hooks:
  - id: isort
    args: [
      '--check',
      '--diff',
    ]
