# Generated by Django 3.1.5 on 2022-04-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='scope_ct',
            new_name='scope_type',
        ),
    ]
