# Generated by Django 3.1.5 on 2022-04-28 07:23

from django.db import migrations, models
import django.db.models.deletion
import hafizhlab.challenges.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='scope_ct',
            new_name='scope_type',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='scope_type',
            field=models.ForeignKey(
                limit_choices_to=hafizhlab.challenges.models.scope_type_choices_q,
                on_delete=django.db.models.deletion.PROTECT,
                to='contenttypes.contenttype',
            ),
        ),
    ]
