# Generated by Django 3.1.5 on 2021-01-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hafizhlab.games.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.PositiveSmallIntegerField(choices=[(1, 'Single Player'), (2, 'Multi Player')])),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(default=hafizhlab.games.models.generate_challenge, on_delete=django.db.models.deletion.PROTECT, to='challenges.challenge')),
            ],
        ),
    ]
