# Generated by Django 3.1.5 on 2021-01-29 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hafizhlab.games.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('public_code', models.CharField(default=hafizhlab.games.models.generate_public_code, editable=False, max_length=4)),
                ('mode', models.CharField(choices=[('single', 'Single Player'), ('multi', 'Multi Player')], default='single', max_length=6)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(default=hafizhlab.games.models.generate_challenge, on_delete=django.db.models.deletion.PROTECT, to='challenges.challenge')),
            ],
        ),
    ]
