# Generated by Django 3.1.5 on 2021-01-27 07:37

from os import path
import pickle

from django.db import migrations


PICKLE_FILE_PATH = path.abspath(path.splitext(__file__)[0] + '.pickle4')

def load_quran_data(apps, schema_editor):
    """Load quran data from pickle file of quran data
    from https://api.alquran.cloud/v1/quran/quran-simple.
    """

    Juz = apps.get_model('quran', 'Juz')
    Surah = apps.get_model('quran', 'Surah')
    Ayah = apps.get_model('quran', 'Ayah')

    Juz.objects.bulk_create(
        Juz(id=juz_id)
        for juz_id in range(1, 31)
    )

    with open(PICKLE_FILE_PATH, 'rb') as f:
        surahs = pickle.load(f)

    Surah.objects.bulk_create(
        Surah(
            id=surah['number'],
            name=surah['name'],
            english_name=surah['englishName'],
        )
        for surah in surahs
    )

    Ayah.objects.bulk_create(
        Ayah(
            juz_id=ayah['juz'],
            surah_id=surah['number'],
            number=ayah['numberInSurah'],
            text=ayah['text'],
        )
        for surah in surahs for ayah in surah['ayahs']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_quran_data),
    ]
