name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  django_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Get pip cache dir
        id: pip-cache-location
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip Project Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache-location.outputs.dir }}
          key: ${{ runner.os}}-pip-${{ hashFiles('**/dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run Django tests with coverage
        run: |
          coverage run manage.py test
          coverage report -m
